name: Build TWRP Recovery

on:
  push:
    branches: [ android-14 ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        device: [ marble ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          depth: 1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y adb autoconf automake axel bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf htop lib32ncurses5-dev lib32readline-dev lib32z1-dev libc6-dev-i386 libffi-dev libgl1-mesa-dev libncurses5-dev libsdl1.2-dev libssl-dev libtool libxml2-dev lzop maven ncurses-dev openjdk-8-jdk pngcrush python python3.8 rsync schedtool squashfs-tools tmux unzip w3m xsltproc zip zlib1g-dev

      - name: Sync Source Code
        run: |
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14
          repo sync

      - name: Prepare Device Tree
        run: |
          git clone https://github.com/YuKongA/device_xiaomi_marble_TWRP.git device/vendor/marble

      - name: Start Build
        env:
          ALLOW_MISSING_DEPENDENCIES: true
          LC_ALL: C
        run: |
          . build/envsetup.sh
          lunch twrp_${{ matrix.device }}-eng
          mka recoveryimage

      - name: Upload Recovery Image
        uses: actions/upload-artifact@v2
        with:
          name: TWRP-Recovery-${{ matrix.device }}
          path: out/target/product/${{ matrix.device }}/recovery.img
